### PR TITLE
Centered the feedback form

### PR DESCRIPTION
**Pull request by hannesfant**
#1238

### CODE REVIEW

**Comment by kristandre** [comment]
Thank you for the PR. We appreciate you taking the time to fix this bug.

It seems like the style change affected a different page than the one mentioned in the issue #1238.
This is the widget that is missing margin/padding: https://github.com/vektorprogrammet/vektorprogrammet/blob/fix_feedback_margin/app/Resources/views/widgets/feedback_widget.html.twig

If you log into https://fix-feedback-margin.staging.vektorprogrammet.no/kontrollpanel (username: admin, password: 1234) and scroll down to the bottom of the page you will find the feedback widget (`Send en melding til IT-teamet!`). This widget does not have the same margin as the other widgets, which makes it unaligned and out of position:

image

By closer inspection it looks like this widget is missing a `<div class="col-12 col-md-4 col-xxxl-4">`-wrapper around the `<div class="card">` here:

image

For comparison, this is an other widget which has the correct margin: https://github.com/vektorprogrammet/vektorprogrammet/blob/fix_feedback_margin/app/Resources/views/widgets/available_surveys_widget.html.twig

To fix #1238 the Feedback widget must be wrapped in a `<div class="col-12 col-md-4 col-xxxl-4">`: https://github.com/vektorprogrammet/vektorprogrammet/blob/fix_feedback_margin/app/Resources/views/widgets/feedback_widget.html.twig

**Comment by hannesfant** [comment]
That's actually really odd, I just added a style property to the html element for the card's container. Is the same code snippet being re-used somewhere else on the app?

**Comment by kristandre** [comment]
Yes, the feedback widget is used on the feedback admin page https://github.com/vektorprogrammet/vektorprogrammet/blob/2d1a312aead6b3fe1db3753715654b6d083db8fa/app/Resources/views/feedback_admin/feedback_admin_index.html.twig#L18 as well as the control panel page https://github.com/vektorprogrammet/vektorprogrammet/blob/2d1a312aead6b3fe1db3753715654b6d083db8fa/app/Resources/views/control_panel/index.html.twig#L32


Since the style property was added to the feedback admin page it does not affect the control panel page. It would have been preferable to fix it in the feedback widget itself, so that the styling is reflected on all pages using it.

**Comment by hannesfant** [comment]
Ah, makes sense. I figured it didn't need one since it was already wrapped in one on the /kontrollpanel/feedback page. Should be working as intended now.

**Comment by kristandre** [comment]
Thank you, looks better now:

image

Fixes #1238

**Pull request merged**
